# Generated by Django 4.0.4 on 2022-05-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='produ_name',
            new_name='product_name',
        ),
    ]
